on:
  push:
    branches: [master, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # https://github.com/synle/gha-workflows/blob/main/.github/workflows/pr-format-and-commit-code.yml
    uses: synle/gha-workflows/.github/workflows/pr-format-and-commit-code.yml@main
    with:
      os: ubuntu-latest
